export const cakes = [
  {
    id: 1,
    name: "Chocolate Truffle",
    price: "$20",
    image: "src/assets/images/Menu/chocolate-truffle.jpg",
    category: "Chocolate",
    isSpecial: true,
  },
  {
    id: 2,
    name: "Red Velvet",
    price: "$25",
    image: "src/assets/images/Menu/red-velvet.jpg",
    category: "Velvet",
    isSpecial: false,
  },
  {
    id: 3,
    name: "Classic Cheesecake",
    price: "$18",
    image: "src/assets/images/Menu/Classic Cheesecake.jpg",
    category: "Cheesecake",
    isSpecial: true,
  },
  {
    id: 4,
    name: "Black Forest",
    price: "$22",
    image: "src/assets/images/Menu/black-forest.jpg",
    category: "Chocolate",
    isSpecial: false,
  },
  {
    id: 5,
    name: "Strawberry Shortcake",
    price: "$19",
    image: "src/assets/images/Menu/cherries-strawberries.jpg",
    category: "Fruity",
    isSpecial: false,
  },
  {
    id: 6,
    name: "Blueberry Cheesecake",
    price: "$21",
    image: "src/assets/images/Menu/blueberry-cheese-cake.jpg",
    category: "Cheesecake",
    isSpecial: false,
  },
  {
    id: 7,
    name: "Carrot Cake",
    price: "$17",
    image: "src/assets/images/Menu/carrot-cake.jpg",
    category: "Vegetable",
    isSpecial: false,
  },
  {
    id: 8,
    name: "Banana Walnut Cake",
    price: "$20",
    image: "src/assets/images/Menu/banana-cake.jpg",
    category: "Nutty",
    isSpecial: false,
  },
  {
    id: 9,
    name: "Mango Mousse Cake",
    price: "$24",
    image: "src/assets/images/Menu/Mango Mousse Cake.avif",
    category: "Fruity",
    isSpecial: true,
  },
  {
    id: 10,
    name: "Coffee Walnut Cake",
    price: "$23",
    image: "src/assets/images/Menu/Coffee Walnut Cake.jpg",
    category: "Nutty",
    isSpecial: false,
  },
  {
    id: 11,
    name: "Tiramisu",
    price: "$28",
    image: "src/assets/images/Menu/tiramisu-cake.jpg",
    category: "Coffee",
    isSpecial: true,
  },
  {
    id: 12,
    name: "Lemon Drizzle Cake",
    price: "$16",
    image: "src/assets/images/Menu/lemon-cake.jpg",
    category: "Citrus",
    isSpecial: false,
  },
  {
    id: 13,
    name: "Coconut Cream Cake",
    price: "$22",
    image: "src/assets/images/Menu/latin-american-food-coconut.avif",
    category: "Tropical",
    isSpecial: true,
  },
  {
    id: 14,
    name: "Peanut Butter Cake",
    price: "$21",
    image: "src/assets/images/Menu/Peanut Butter Cake.jpg",
    category: "Nutty",
    isSpecial: false,
  },
  {
    id: 15,
    name: "Pineapple Upside-Down Cake",
    price: "$20",
    image: "src/assets/images/Menu/Pineapple Upside-Down Cake.avif",
    category: "Tropical",
    isSpecial: true,
  },
];
